	
var langItems={
noListsPublished:'No reports published.',
liveUpdateActive:'Live Update active',
pdfResults :'Complete Results as PDF',
noEntries:'Sorry, no entries found.',
showAll:'show all [x] participants',
showMore:'show more',
searchPlaceHolder:'Search name, bib, club, etc.',
mode1:'Show Leaders & Favorites',
mode2:'Show All',
mode3:'Show Favorites Only',
mode4:'Search Results',
search:'Search',
back:'Back to Overview',
allContests:'General',
writeComment:'Write a comment',
commentNamePH:'Your Name',
commentTextPH:'Your Comment',
commentWhy:'What for?',
commentWhy2:'Congratulate on a good achievement or leave some greeting.',
commentRules:'Rules:',
commentRules2:'Only friendly, positive comments, no defamations, insults, etc. In order to avoid misuse, we save your IP address.',
commentSend:'Send',
detailsCertificates:'Certificates',
detailsLinks:'Links',
detailsPhotos:'Photos',
detailsComments:'Comments',
detailsDetails:'Result Details',
detailsFav:'Favorite',
detailsNoFav:'No Favorite',
detailsBack:'back',
social2:'Share your result with your friends.',
markFavorite:'Mark/unmark as favorite',
showFavorites:'Show favorites only',
CommentsInfo:'[x] Comment(s)',
LiveUpdateContinue1:'Are you still there?',
LiveUpdateContinue2:'Live Update has been paused. Please move the mouse to resume.',
LiveUpdateContinue3:'Live Update has been paused. Please touch the screen to resume.',
CurrentResult:'Current Result',
FilterAll:'Show All',
FilterIgnore:'Overall',
SplitsLabel1:'Legs',
SplitsLabel2:'Splits',
SplitsLabel3:'Prediction',
SplitsHead1:'Time',
SplitsHead2:'Speed',
SplitsHead3:'Overall',
SplitsHead4:'Gender',
SplitsHead5:'Age Group',
SplitsHead6:'Time of Day',
SplitsHead7:'Gun Time',
SplitsHead8:'Chip Time',
SplitsHead9:'Sector'
};